version: "3"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ./..:/app
      - /app/node_modules
    ports:
      - 3000:3000
    tty: true
